### ISSUE TITLE
General repo description

### ISSUE THREAD

**Issue by miherlosev** [miherlosev/tmp#12]
`testcafe-hammerhead` is a powerful web-proxy used as a core for the [TestCafe](https://github.com/devexpress/testcafe) testing framework. 

## Installation
`npm install testcafe-hammerhead --save`

## Core Conceps
`testcafe-hammerhead` is an URL-rewritten proxy. It means that proxy rewrite all properties  of the  appropriate JavaScript objects that contains URL value (`Location`, `HTMLLinkElement.href` and etc). You can see it by opening browser DevTools and inpect some element. 
On the over hand the proxied web does not know that it is opened under proxy. The proxy catches the access to the all url-contained properties and provide the origin values.

## Example
See [Playground example](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/playground/server.js) in our repository.

## Features
* HTTP/HTTPS request
* WebSockets, EventSource
* file upload
* request events (`onRequest`, `onResponse`)
* bypass requests
* custom UI on web page

## Contributing and Issues
* if your web site works in different way with and without proxy then it is an issue. 
* if you find a problem please provide a public link to your website or create a simple example to reproduce.
* all PR with bug fixes should have tests (may be rare exceptions)

**Comment by VasilyStrelyaev** [comment]
`testcafe-hammerhead` is a powerful Web proxy used as a core for the [TestCafe](https://github.com/devexpress/testcafe) testing framework.

## Installation

```
npm install testcafe-hammerhead --save
```

## Core Concepts

`testcafe-hammerhead` is a URL-rewriting proxy. This means that it rewrites all properties of the appropriate JavaScript objects that contain a URL value (`Location`, `HTMLLinkElement.href`, etc). You can see it if you open a proxied page, invoke the browser's DevTools and inspect any element.

In addition, the proxied web page does not know that it is opened under a proxy. The proxy intercepts access attempts to all URL-containing properties and provides the original values.

## Example

See the [Playground example](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/playground/server.js) in our repository.

## Features

* HTTP/HTTPS requests
* WebSockets, EventSource
* file upload
* request events (`onRequest`, `onResponse`)
* bypass requests
* custom UI on web page

## Contributing and Issues

* if your website works differently with and without a proxy, create an issue.
* if you find a problem, please provide a public link to your website or create a simple example to reproduce it.
* all PRs with bug fixes should contain tests (there may be rare exceptions)

**Comment by VasilyStrelyaev** [comment]
`testcafe-hammerhead` is a powerful Web proxy used as a core for the [TestCafe](https://github.com/devexpress/testcafe) testing framework.

## Core Concepts

`testcafe-hammerhead` is a URL-rewriting proxy. This means that it rewrites all properties of the appropriate JavaScript objects that contain a URL value (`Location`, `HTMLLinkElement.href`, etc). You can see it if you open a proxied page, invoke the browser's DevTools and inspect any element.

In addition, the proxied web page does not know that it is opened under a proxy. The proxy intercepts access attempts to all URL-containing properties and provides the original values.

## First Look
1. Install the Hammerhead proxy (`npm install testcafe-hammerhead --save`), 
2. Build it (`gulp run build`)
3. Run the [Hammerhead playground](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/playground/server.js) (`npm run http-playground`) to see our proxy in action.

This opens a playground page where you can specify a webpage to proxy. Enter the page URL and hit **Proxy!**.

## Features

* HTTP/HTTPS requests
* WebSockets, EventSource
* file upload
* request events (`onRequest`, `onResponse`)
* bypass requests
* custom UI on the web page

## Reporting Issues and Contributing

* If your website works differently with and without a proxy, create an issue.
* If you find a problem, please provide a public link to your website or create a simple example to reproduce it.
* All PRs with bug fixes should contain tests (there may be rare exceptions)

**Comment by VasilyStrelyaev** [comment]
## First Look
1. Clone the Hammerhead repository (`git clone https://github.com/DevExpress/testcafe-hammerhead.git`), 
2. Build it (`gulp run build`)
3. Run the [Hammerhead playground](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/playground/server.js) (`npm run http-playground`) to see our proxy in action.

This opens a playground page where you can specify a webpage to proxy. Enter the page URL and hit **Proxy!**.
