### ISSUE TITLE
0.19.2 change log

### ISSUE THREAD

**Issue by miherlosev** [miherlosev/tmp#3]
#### :gear: Added possibility to exclude specified routes from proxying using the '--proxy-bypass' option ([#1791](https://github.com/DevExpress/testcafe/issues/1791))

```js
testcafe chrome my-tests/**/*.js --proxy proxy.corp.mycompany.com --proxy-bypass direct1.mycompany.com,direct2.mycomparny.com
```

### Bug Fixes

* Restored the internal screenshots API compatibility for legacy tests ([#2235](https://github.com/DevExpress/testcafe/issues/2235))
* Update the list of available devices for emulation in Google Chome ([#2257](https://github.com/DevExpress/testcafe/issues/2257))
* Fixed touch events emulation ([#2268](https://github.com/DevExpress/testcafe/issues/2268))
* Now the `evetn.relatedTarget` property correctly is set for the emulated focus and drag events ([#2197](https://github.com/DevExpress/testcafe/issues/2197))
* Now the `event.detail` property correctly is set for the emulated mouse events ([#2232](https://github.com/DevExpress/testcafe/issues/2232))
* `Element.innerHTML` property is now processed correctly for special case ([testcafe-hammerhead/#1538](https://github.com/DevExpress/testcafe-hammerhead/issues/1538))
* Now iframe location has correct value then it is not initialized([testcafe-hammerhead/#1531](https://github.com/devexpress/testcafe-hammerhead/issues/1531))
* Trailing slash is added now to test page url if it is necessary ([#2005](https://github.com/DevExpress/testcafe/issues/2005))
* `focus` event is not called for disabled input now ([#2123](https://github.com/devexpress/testcafe/issues/2123))

**Comment by VasilyStrelyaev** [comment]
Enhancements

Added support for browser providers from private repositories (#2221)

Bug Fixes

Restored the screenshot functionality in legacy tests (#2235)
Updated the list of devices available for emulation in Google Chrome (#2257)
Fixed touch events emulation (#2268)
Now the `event.relatedTarget` property is set correctly for the emulated focus and drag events (#2197)
Now the `event.detail` property is set correctly for the emulated mouse events (#2232)
The `Element.innerHTML` property is now processed correctly in certain special cases (testcafe-hammerhead/#1538)
Now the iframe location has the correct value when it is not initialized (testcafe-hammerhead/#1531)
A trailing slash is now added to test page URL if it is necessary (#2005)
The `focus` event is not called for a disabled input now (#2123)
