### ISSUE TITLE
Change log 0.20.1

### ISSUE THREAD

**Issue by miherlosev** [miherlosev/tmp#7]
#### :gear: Typescript definitions for new features from `0.20.0` has been added ([2428](https://github.com/DevExpress/testcafe/issues/2428))

Bug fixes:
* Now sites with overridden `Element.prototype.mathes` method  work properly [#2241](https://github.com/DevExpress/testcafe/issues/2241)
* `window.Blob` returns a correct result now when Array of ArrayBuffer is passed as parameter ([testcafe-hammerhead/#1599](https://github.com/DevExpress/testcafe-hammerhead/issues/1599))
* Firefox [Shield](https://support.mozilla.org/en-US/kb/shield) popup is not shown during test execution now ([#2421](https://github.com/DevExpress/testcafe/pull/2421))

**Comment by VasilyStrelyaev** [comment]
⚙️ Typescript definitions for new features from v0.20.0 have been added (#2428)

### Bug fixes

* Now sites with the overridden `Element.prototype.matches` method work properly #2241
* `window.Blob` now returns a correct result when Array of `ArrayBuffer` is passed as a parameter (testcafe-hammerhead/#1599)
* Firefox Shield popup is not shown during test execution now (#2421)
