### ISSUE TITLE
0.20.3

### ISSUE THREAD

**Issue by miherlosev** [miherlosev/tmp#8]
### Bug fixes

* Selection into contenteditable `div` now works properly for special case ([#2365](https://github.com/DevExpress/testcafe/issues/2365))
* Fix collision related to several `moment-duration-format` package versions ([#1750](https://github.com/DevExpress/testcafe/issues/1750))
* TestCafe now report a warning when taking screenshots with same paths ([#2213](https://github.com/DevExpress/testcafe/issues/2213))
* Regression related to wrong processing `document.write` in IE11 is fixed now ([2469](https://github.com/DevExpress/testcafe/issues/2469))
* Out of memory crash on calling `console` methods is fixed now ([testcafe-hammerhead/#1546](https://github.com/DevExpress/testcafe-hammerhead/issues/1546))

**Comment by VasilyStrelyaev** [comment]
## v0.20.3 (2018-6-6)

### Enhancements 

#### ⚙️ Add TS definitions to the Docker image ([#2481](https://github.com/DevExpress/testcafe/pull/2481))

### Bug fixes

* Selection in a `contenteditable` `div` now works properly in a specific scenario ([#2365](https://github.com/DevExpress/testcafe/issues/2365))
* A collision related to several `moment-duration-format` package versions is now fixed ([#1750](https://github.com/DevExpress/testcafe/issues/1750))
* TestCafe now reports a warning when saving several screenshots at the same path ([#2213](https://github.com/DevExpress/testcafe/issues/2213))
* A regression related to wrongly processed `document.write` in IE11 is now fixed ([#2469](https://github.com/DevExpress/testcafe/issues/2469))
* An out of memory crash on calling console methods is now fixed ([testcafe-hammerhead/#1546](https://github.com/DevExpress/testcafe-hammerhead/issues/1546))

**Comment by miherlosev** [comment]
More two entries for `Bug fixes` section:
* `Click` action for an element with 1px height or width works properly now ([2020](https://github.com/DevExpress/testcafe/issues/2020))
* Touch emulation for the latest Google Chrome was fixed ([#2448](https://github.com/DevExpress/testcafe/issues/2448))

**Comment by VasilyStrelyaev** [comment]
okay
